CREATE TABLE USER_ACCOUNT (
    id SMALLINT(255) UNSIGNED NOT NULL AUTO_INCREMENT,
    Email VARCHAR(200) NOT NULL,
    FirstName VARCHAR(50),
    LastName VARCHAR(50),
    Phone VARCHAR(15),
    StreetAddress VARCHAR(100),
    City VARCHAR(50),
    State VARCHAR(20),
    Zip MEDIUMINT(255) UNSIGNED,
    Salt VARCHAR(20),
    Hash VARCHAR(64),
    UNIQUE KEY(Email),
    PRIMARY KEY(Id)
);

CREATE TABLE PROFILE (
    id SMALLINT(255) UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    AcctID SMALLINT(255) UNSIGNED NOT NULL,
    PRIMARY KEY(Id),
    FOREIGN KEY(AcctID) REFERENCES USER_ACCOUNT(id) ON DELETE CASCADE
);

CREATE TABLE MOVIE (
    id SMALLINT(255) UNSIGNED NOT NULL AUTO_INCREMENT,
    Name VARCHAR(50) NOT NULL,
    YearReleased SMALLINT(255) UNSIGNED,
    Runtime VARCHAR(10),
    Description VARCHAR(500),
    PRIMARY KEY(Id)
);

CREATE TABLE VIEWS_MOVIE (
    MovieID SMALLINT(255) UNSIGNED NOT NULL,
    ProfileID SMALLINT(255) UNSIGNED NOT NULL,
    PercentComplete TINYINT(255) UNSIGNED,
    PRIMARY KEY (MovieID, ProfileID)
);